<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sstlfsj</groupId>
    <artifactId>fibra</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>fibra-spring-boot-starter</artifactId>
  <name>Fibra Spring Boot Starter</name>
  <description>Fibra Spring Boot 的无源码依赖入口。</description>
  <properties>
    <maven.deploy.skip>false</maven.deploy.skip>
    <maven.source.skip>false</maven.source.skip>
    <maven.javadoc.skip>false</maven.javadoc.skip>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-spring-boot-autoconfigure</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-empty-javadocs</id>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <classifier>javadoc</classifier>
              <classesDirectory>${project.build.directory}/empty-javadocs</classesDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
