<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sstlfsj</groupId>
    <artifactId>fibra</artifactId>
    <version>${revision}</version>
    <relativePath>../../../pom.xml</relativePath>
  </parent>
  <artifactId>fibra-fs-local</artifactId>
  <name>Fibra Local File System Plugin</name>
  <description>受根目录约束的本地文件系统与 spill provider 插件。</description>
  <properties>
    <maven.deploy.skip>false</maven.deploy.skip>
    <maven.source.skip>false</maven.source.skip>
    <maven.javadoc.skip>false</maven.javadoc.skip>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-fs</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-tool-api</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
