<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sstlfsj</groupId>
    <artifactId>fibra</artifactId>
    <version>${revision}</version>
    <relativePath>../../../pom.xml</relativePath>
  </parent>
  <artifactId>fibra-config-client-test-plugin</artifactId>
  <name>Fibra Config Client Test Plugin</name>
  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
    <maven.source.skip>true</maven.source.skip>
    <maven.javadoc.skip>true</maven.javadoc.skip>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-bridge</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-tool-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-storage</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>META-INF/fibra/plugin.yaml</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
