package com.sstlfsj.fibra.parity;

import com.sstlfsj.fibra.Context;
import com.sstlfsj.fibra.artifact.ArtifactStore;
import com.sstlfsj.fibra.bridge.ContributionBridge;
import com.sstlfsj.fibra.config.DesiredGraph;
import com.sstlfsj.fibra.engine.FibraEngine;
import com.sstlfsj.fibra.registry.PluginRegistry;
import com.sstlfsj.fibra.runtime.FibraRuntime;
import com.sstlfsj.fibra.runtime.java.JavaPluginRuntimeAdapter;
import com.sstlfsj.fibra.runtime.node.NodePluginRuntimeAdapter;
import com.sstlfsj.fibra.spring.FibraServiceBridge;
import com.sstlfsj.fibra.spring.boot.FibraAutoConfiguration;
import org.junit.jupiter.api.Test;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.lang.reflect.Modifier;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.jar.JarFile;
import java.util.spi.ToolProvider;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ApiSignatureBaselineTest {
    private static final List<ModuleApi> MODULES = List.of(
        new ModuleApi("fibra-api", Context.class, "com.sstlfsj.fibra."),
        new ModuleApi("fibra-core", FibraRuntime.class, "com.sstlfsj.fibra.runtime."),
        new ModuleApi("fibra-config", DesiredGraph.class, "com.sstlfsj.fibra.config."),
        new ModuleApi("fibra-artifact", ArtifactStore.class,
            "com.sstlfsj.fibra.artifact."),
        new ModuleApi("fibra-engine", FibraEngine.class, "com.sstlfsj.fibra.engine."),
        new ModuleApi("fibra-bridge", ContributionBridge.class,
            "com.sstlfsj.fibra.bridge."),
        new ModuleApi("fibra-runtime-java", JavaPluginRuntimeAdapter.class,
            "com.sstlfsj.fibra.runtime.java."),
        new ModuleApi("fibra-runtime-node", NodePluginRuntimeAdapter.class,
            "com.sstlfsj.fibra.runtime.node."),
        new ModuleApi("fibra-registry", PluginRegistry.class,
            "com.sstlfsj.fibra.registry."),
        new ModuleApi("fibra-spring", FibraServiceBridge.class,
            "com.sstlfsj.fibra.spring."),
        new ModuleApi("fibra-spring-boot-starter", FibraAutoConfiguration.class,
            "com.sstlfsj.fibra.spring.boot."));

    @Test
    void publicApiMatchesCommittedJavapBaselines() throws Exception {
        for (var module : MODULES) {
            assertBaseline(module);
        }
    }

    private static void assertBaseline(ModuleApi module) throws Exception {
        var location = moduleLocation(module.anchor());
        var names = discoverPublicTypes(location, module.anchor().getClassLoader()).stream()
            .filter(name -> name.startsWith(module.packagePrefix())).toList();
        var actual = normalize(javap(module.name(), names, location));
        var baseline = repositoryRoot().resolve("docs/api/" + module.name()
            + "-public-signatures.txt");
        if (Boolean.getBoolean("fibra.updateApiBaseline")) {
            Files.writeString(baseline, actual);
            return;
        }
        assertEquals(normalize(Files.readString(baseline)), actual,
            module.name() + " public API changed without an accepted baseline update");
    }

    private static List<String> discoverPublicTypes(Path location,
                                                     ClassLoader classLoader)
        throws Exception {
        var candidates = new ArrayList<String>();
        if (Files.isDirectory(location)) {
            try (var paths = Files.walk(location)) {
                paths.filter(path -> path.toString().endsWith(".class"))
                    .map(path -> location.relativize(path).toString())
                    .map(name -> name.substring(0, name.length() - 6).replace('/', '.'))
                    .forEach(candidates::add);
            }
        } else {
            try (var jar = new JarFile(location.toFile())) {
                jar.stream().filter(entry -> entry.getName().endsWith(".class"))
                    .map(entry -> entry.getName().substring(0,
                        entry.getName().length() - 6).replace('/', '.'))
                    .forEach(candidates::add);
            }
        }
        return candidates.stream().filter(name -> !name.equals("module-info"))
            .filter(name -> isPublic(name, classLoader)).sorted().toList();
    }

    private static boolean isPublic(String name, ClassLoader classLoader) {
        try {
            return Modifier.isPublic(Class.forName(name, false, classLoader).getModifiers());
        } catch (ClassNotFoundException exception) {
            throw new IllegalStateException(exception);
        }
    }

    private static String javap(String module, List<String> names, Path location) {
        var tool = ToolProvider.findFirst("javap").orElseThrow();
        var result = new StringBuilder("# ").append(module)
            .append(" public and protected signatures; generated by JDK javap -protected\n");
        for (var name : names) {
            var output = new StringWriter();
            var errors = new StringWriter();
            int exit = tool.run(new PrintWriter(output), new PrintWriter(errors),
                "-protected", "-classpath", location.toString(), name);
            if (exit != 0) {
                throw new IllegalStateException(errors.toString());
            }
            result.append("## ").append(name).append('\n')
                .append(output.toString().replace("\r\n", "\n"));
        }
        return result.toString();
    }

    private static String normalize(String value) {
        return value.replace("\r\n", "\n").stripTrailing() + "\n";
    }

    private static Path moduleLocation(Class<?> anchor) {
        try {
            return Path.of(anchor.getProtectionDomain().getCodeSource().getLocation().toURI());
        } catch (URISyntaxException exception) {
            throw new IllegalStateException(exception);
        }
    }

    private static Path repositoryRoot() {
        var current = Path.of("").toAbsolutePath();
        while (current != null && !Files.isDirectory(current.resolve("fibra-api"))) {
            current = current.getParent();
        }
        if (current == null) {
            throw new IllegalStateException("cannot locate Fibra reactor root");
        }
        return current;
    }

    private record ModuleApi(String name, Class<?> anchor, String packagePrefix) {
    }
}
