package com.sstlfsj.fibra.parity;

import com.sstlfsj.fibra.Context;
import com.sstlfsj.fibra.runtime.FibraRuntime;
import org.junit.jupiter.api.Test;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.lang.reflect.Modifier;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.jar.JarFile;
import java.util.function.Predicate;
import java.util.spi.ToolProvider;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ApiSignatureBaselineTest {
    private static final String HEADER =
        "# fibra-api public and protected signatures; generated by JDK javap -protected\n";
    private static final String CORE_HEADER =
        "# fibra-core supported public and protected signatures; generated by JDK javap -protected\n";

    @Test
    void publicApiMatchesCommittedJavapBaseline() throws Exception {
        var baseline = repositoryRoot().resolve("docs/api/fibra-api-public-signatures.txt");
        assertBaseline(baseline, HEADER, Context.class, name -> true);
    }

    @Test
    void corePublicApiMatchesCommittedJavapBaseline() throws Exception {
        var baseline = repositoryRoot().resolve("docs/api/fibra-core-public-signatures.txt");
        var location = moduleLocation(FibraRuntime.class);
        var publicTypes = discoverPublicTypes(location, FibraRuntime.class.getClassLoader());
        var unexpected = publicTypes.stream()
            .filter(name -> !name.startsWith("com.sstlfsj.fibra.runtime."))
            .filter(name -> !name.startsWith("com.sstlfsj.fibra.internal."))
            .toList();

        assertEquals(List.of(), unexpected,
            "fibra-core 出现未归入 runtime 或 internal 边界的公开类型");
        assertBaseline(baseline, CORE_HEADER, FibraRuntime.class,
            name -> name.startsWith("com.sstlfsj.fibra.runtime."));
    }

    private static void assertBaseline(Path baseline, String header, Class<?> anchor,
                                       Predicate<String> includedType) throws Exception {
        var expected = normalize(Files.readString(baseline));
        var names = expected.lines()
            .filter(line -> line.startsWith("## "))
            .map(line -> line.substring(3))
            .toList();
        var location = moduleLocation(anchor);

        assertEquals(names, discoverPublicTypes(location, anchor.getClassLoader()).stream()
                .filter(includedType)
                .toList(),
            "公开类型集合已变化；必须先完成 API 审核并显式更新基线");
        assertEquals(expected, normalize(javap(header, names, location)),
            "公开签名已变化；必须先完成 API 审核并显式更新基线");
    }

    private static String normalize(String value) {
        return value.replace("\r\n", "\n").stripTrailing() + "\n";
    }

    private static List<String> discoverPublicTypes(Path location, ClassLoader classLoader)
        throws Exception {
        var candidates = new ArrayList<String>();
        if (Files.isDirectory(location)) {
            try (var paths = Files.walk(location)) {
                paths.filter(path -> path.toString().endsWith(".class"))
                    .map(path -> location.relativize(path).toString())
                    .map(name -> name.substring(0, name.length() - 6).replace('/', '.'))
                    .forEach(candidates::add);
            }
        } else {
            try (var jar = new JarFile(location.toFile())) {
                jar.stream().filter(entry -> entry.getName().endsWith(".class"))
                    .map(entry -> entry.getName().substring(0, entry.getName().length() - 6)
                        .replace('/', '.'))
                    .forEach(candidates::add);
            }
        }
        return candidates.stream()
            .filter(name -> !name.equals("module-info"))
            .filter(name -> isPublic(name, classLoader))
            .sorted()
            .toList();
    }

    private static boolean isPublic(String name, ClassLoader classLoader) {
        try {
            return Modifier.isPublic(Class.forName(name, false, classLoader).getModifiers());
        } catch (ClassNotFoundException exception) {
            throw new IllegalStateException(exception);
        }
    }

    private static String javap(String header, List<String> names, Path location) {
        var tool = ToolProvider.findFirst("javap").orElseThrow();
        var result = new StringBuilder(header);
        for (var name : names) {
            var output = new StringWriter();
            var errors = new StringWriter();
            int exit = tool.run(new PrintWriter(output), new PrintWriter(errors),
                "-protected", "-classpath", location.toString(), name);
            if (exit != 0) {
                throw new IllegalStateException(errors.toString());
            }
            result.append("## ").append(name).append('\n')
                .append(output.toString().replace("\r\n", "\n"));
        }
        return result.toString();
    }

    private static Path moduleLocation(Class<?> anchor) {
        try {
            return Path.of(anchor.getProtectionDomain().getCodeSource().getLocation().toURI());
        } catch (URISyntaxException exception) {
            throw new IllegalStateException(exception);
        }
    }

    private static Path repositoryRoot() {
        var current = Path.of(System.getProperty("user.dir")).toAbsolutePath();
        return current.getFileName().toString().equals("fibra-parity-tests")
            ? current.getParent()
            : current;
    }
}
