- id: fibra-example-consumer
  name: fibra-example-consumer
  inject: [example.provider.greeting]
  isolate:
    example.provider.greeting: example
- id: fibra-example-provider
  name: fibra-example-provider
  config:
    prefix: provider
  isolate:
    example.provider.greeting: example
