<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>verification.distribution</groupId>
    <artifactId>fibra-distribution-verification</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>spring-boot-application</artifactId>
  <dependencies>
    <dependency>
      <groupId>com.sstlfsj</groupId><artifactId>fibra-spring-boot-starter</artifactId>
      <version>${fibra.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId>
      <version>${spring-boot.version}</version><scope>test</scope>
    </dependency>
  </dependencies>
</project>
