<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sstlfsj</groupId>
    <artifactId>fibra</artifactId>
    <version>${revision}</version>
    <relativePath>../../../pom.xml</relativePath>
  </parent>
  <artifactId>fibra-plugins-acceptance-host</artifactId>
  <name>Fibra Plugins Acceptance Host</name>
  <dependencies>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-tool-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-runtime-java</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-registry</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-fs</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-fs-local</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-tool-fs</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-subprocess</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-subprocess-local</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-tool-fs-search</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-shell</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-shell-local</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-tool-shell</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-storage</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-storage-json</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sstlfsj</groupId>
      <artifactId>fibra-tool-storage</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>stage-plugin-artifacts</id>
            <phase>process-test-resources</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <includeGroupIds>com.sstlfsj</includeGroupIds>
              <includeArtifactIds>fibra-fs,fibra-fs-local,fibra-tool-fs,fibra-subprocess,fibra-subprocess-local,fibra-tool-fs-search,fibra-shell,fibra-shell-local,fibra-tool-shell,fibra-storage,fibra-storage-json,fibra-tool-storage</includeArtifactIds>
              <outputDirectory>${project.build.directory}/plugin-artifacts</outputDirectory>
              <overWriteReleases>true</overWriteReleases>
              <overWriteSnapshots>true</overWriteSnapshots>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <classpathDependencyExcludes>
            <classpathDependencyExclude>com.sstlfsj:fibra-fs</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-fs-local</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-tool-fs</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-subprocess</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-subprocess-local</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-tool-fs-search</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-shell</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-shell-local</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-tool-shell</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-storage</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-storage-json</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-tool-storage</classpathDependencyExclude>
          </classpathDependencyExcludes>
          <systemPropertyVariables>
            <fibra.pluginArtifacts>${project.build.directory}/plugin-artifacts</fibra.pluginArtifacts>
          </systemPropertyVariables>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <classpathDependencyExcludes>
            <classpathDependencyExclude>com.sstlfsj:fibra-fs</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-fs-local</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-tool-fs</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-subprocess</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-subprocess-local</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-tool-fs-search</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-shell</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-shell-local</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-tool-shell</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-storage</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-storage-json</classpathDependencyExclude>
            <classpathDependencyExclude>com.sstlfsj:fibra-tool-storage</classpathDependencyExclude>
          </classpathDependencyExcludes>
          <systemPropertyVariables>
            <fibra.pluginArtifacts>${project.build.directory}/plugin-artifacts</fibra.pluginArtifacts>
          </systemPropertyVariables>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
